version: '3.8'

services:
  app:
    build: .
    container_name: hits-app
    ports:
      - "8023:8000"
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: hits-mongodb
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=hits_db
    ports:
      - "27017:27017"

volumes:
  mongodb_data: 